### ISSUE TITLE
与web系统集成问题

### ISSUE THREAD

**Issue by ghost** [sjdy521/pfwx#1]
最近整了一个类App的页面如下:
http://hmcy.net/theme-setup2/examples/login/index.html
如果想实现手机扫码确认登陆，应该如何集成你这个方案?

**Comment by hexsum** [comment]
我提供相关的api（包括获取登录二维码，获取好友信息，接收和发送消息等）这样OK吗？不知道你最终像做出来的是什么效果

发自网易邮箱大师
在2015年04月15日 12:16，jnuc093 写道:

最近整了一个类App的页面如下:
http://hmcy.net/theme-setup2/examples/login/index.html
如果想实现手机扫码确认登陆，应该如何集成你这个方案?

**Comment by ghost** [comment]
我是想整个类似于 网页版微信登陆的效果：
1、前端页面是静态页面，直接部署在github上的(就是这个例子)
2、应该是跨域访问你这个客户端提供的api。
我先试一试你这功能。这种直接登陆的功能需求量还是蛮大的。仅仅一个登陆就行了，现在网页登陆的趋势是不用记密码了。

**Comment by hexsum** [comment]
仅仅一个登录，然后呢？有什么意义吗？不是很明白，希望能够解释的更具体点，如果确实有需求量，也很愿意提供配合支持

**Comment by ghost** [comment]
https://github.com/chanjarster/weixin-java-tools/wiki/CP_demo%E4%BB%A3%E7%A0%81
参考这东东。它仅仅支持订阅号和公众号登陆及其后面的操作。
你的产品要是能支持普通号的登陆就好了。
我的应用场景是这样:
       1、传统企业应用比如CRM系统的微信化改造,用户登陆这块支持微信扫码登陆。
       2、意义在于原来系统有一套成熟的登陆系统有工号和密码，如果直接能实现以微信客户端的登陆会更方便。
       3、当然首先有个注册机制比如CRM系统后台有个确认是否此微信号能否登陆到此系统中。

**Comment by hexsum** [comment]
@jnuc093 你说的是"企业系统使用第三方帐号登录"? 那现在的oAuth技术不就可以满足了？而且还是现成的
