### ISSUE TITLE
建议给这个框架起一个较短的容易记忆推广的短名字 :)

### ISSUE THREAD

**Issue by wxg4net** [sjdy521/pfwx#2]
现有名称既有大写又有连接线有点复杂

**Comment by hexsum** [comment]
但这是比较符合cpan命名规范的方式，熟悉perl的人应该不会感觉不适，不熟悉perl的也只能是无缘了:)

**Comment by hexsum** [comment]
@wxg4net 有没有好的别名推荐下？

**Comment by wxg4net** [comment]
我向别人介绍时 代号 sjdy521代表webqq。至于这个项目，考虑用 sjdy521-again 如何 :)

**Comment by hexsum** [comment]
一个叫pfqq 一个叫pfwx 如何～

**Comment by wxg4net** [comment]
@sjdy521 pf = perl framework 的意思么？
感觉不错。

**Comment by hexsum** [comment]
我名字中文缩写是pf，英文缩写也是pf，pf还可以理解成perl fuck...

**Comment by wxg4net** [comment]
晕。pf神了...
