### ISSUE TITLE
请问怎么安装依赖包?还没用过perl呢。

### ISSUE THREAD

**Issue by ghost** [sjdy521/pfwx#3]
➜  Weixin-Client git:(master) ✗ perl Makefile.PL
Warning: prerequisite AnyEvent::HTTP 0 not found.
Warning: prerequisite JSON 0 not found.
Writing Makefile for Weixin::Client
Writing MYMETA.yml and MYMETA.json
➜  Weixin-Client git:(master) ✗ perl -v         

This is perl 5, version 16, subversion 2 (v5.16.2) built for darwin-thread-multi-2level
(with 3 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by hexsum** [comment]
在系统上执行 cpan -i Weixin::Client 就可以自动完成在线安装了
你如果手动安装，就依次执行
perl Makefile.PL
make
make test
make install

**Comment by hexsum** [comment]
@jnuc093 装上了没？

**Comment by ghost** [comment]
cpan -i Weixin::Client 这种方式装好了。谢谢。
